
blank_issues_enabled: false
contact_links:
  - name: Help with installing, configuring and using Netdata.
    url: https://community.netdata.cloud/c/support/13
    about: We offer community-driven support in the respective category of the community forums.
  -  name: Help with developing for the Netdata Agent and it's plugins
     url: https://community.netdata.cloud/c/agent-development/9
     about: If you need help in developing for our open-source Netdata Agent, ask a question on our community forums.
  - name: Feature request
    url: https://community.netdata.cloud/c/feature-requests/7
    about: Make a feature request for Netdata Cloud or the Netdata Agent
  - name: Community
    url: https://netdata.cloud/community
    about: If you don't know where to start, visit our community page!